export const landingDict = {
  es: {
    navFeatures: "Funciones",
    navPricing: "Planes",
    navCommunity: "Comunidad",
    navSupport: "Soporte",
    btnLogin: "Iniciar Sesión",
    btnSignup: "Probar Gratis",
    heroMain: "Toda tu música.",
    heroSub: "Bajo control.",
    heroDesc: "El motor que sincroniza tu música, tus letras y tus luces en tiempo real — para que en el escenario todo se mueva como una sola cosa.",
    heroTags: "Eventos • Repertorios • Recursos • Multitracks • Secuencias",
    btnStart: "Empezar Ahora",
    btnViewPlans: "Ver planes",
    availableOn: "Disponible en",
    webTitle: "Gestión & Ensayo Web",
    webDesc: "Organiza tus eventos, planea repertorios y ensaya con tus stems desde cualquier navegador.",
    desktopTitle: "App Nativa (Windows / Mac)",
    desktopDesc: "La herramienta profesional para reproducir tus secuencias en vivo con latencia cero y máxima estabilidad.",
    premiumMini: "NADA SE COMPARA",
    premiumMain1: "Un mismo marcador mueve tu audio, tus letras",
    premiumMain2: "y tus luces,",
    premiumMain3: "al mismo tiempo.",
    premiumSupport1: "No es una función más. Es",
    premiumSupport2: "cómo se mueve cada show:",
    premiumSupport3: "los marcadores de Bandly DAW disparan la letra en pantalla y la escena de luces, exactamente en el mismo instante.",
    syncBadge1: "Bandly DAW",
    syncBadge1Desc: "Multitracks con latencia cero",
    syncBadge2: "Letras",
    syncBadge2Desc: "Bandly Presenter en pantalla",
    syncBadge3: "Luces",
    syncBadge3Desc: "Bandly Lights (DMX/Art-Net)",
    proPlayerTitle1: "El Único Reproductor de Multitracks Nativo",
    proPlayerTitle2: "para Windows y Mac.",
    proPlayerDesc: "A diferencia de otras plataformas web, Bandly cuenta con su propio motor de audio instalable. Gestiona todos tus multitracks simultáneos con latencia cero. Diseñado específicamente para músicos que necesitan fiabilidad absoluta en el escenario.",
    proFeat1: "Arreglo sin re-exportar",
    proFeat1Desc: "Sáltate el verso 2 o repite el coro con un clic. El audio original nunca se corta — se deshace igual de fácil.",
    proFeat2: "Ruteo multicanal real",
    proFeat2Desc: "Cada pista a la salida física que quieras: click al 3, pistas al 1-2, pads al 5-6. Con ASIO nativo.",
    proFeat3: "EQ de 3 bandas por pista",
    proFeat3Desc: "Ecualiza cada canal desde la misma app, sin consola aparte.",
    proFeat4: "Click con salida propia",
    proFeat4Desc: "Y pre-roll contado por compases antes de entrar.",
    proFeat5: "Sincronización local",
    proFeat5Desc: "Descarga y reproduce sin depender del internet.",
    proFeat6: "Resiliencia de hardware",
    proFeat6Desc: "Si la interfaz se desconecta en pleno show, se reconecta sola.",
    presenterMini: "PROYECCIÓN EN VIVO",
    presenterTitle1: "Bandly Presenter,",
    presenterTitle2: "letras en pantalla sin operador extra.",
    presenterDesc: "La app de escritorio para proyectar letras y contenido durante tus eventos — sincronizada automáticamente con lo que pasa en el DAW, sin que nadie tenga que estar cambiando diapositivas a mano.",
    presenterFeat1: "Sincronización automática",
    presenterFeat1Desc: "Los marcadores de sección del DAW cambian la diapositiva en pantalla solos, en tiempo real.",
    presenterFeat2: "Stage Display",
    presenterFeat2Desc: "Ventana aparte para el escenario: letra actual, siguiente línea y reloj — sin mirar la pantalla de la audiencia.",
    presenterFeat3: "Fondos e imágenes por canción",
    presenterFeat3Desc: "Cada canción con su propio fondo, tipografía y estilo, listos desde antes del evento.",
    mobileTitle1: "Todo tu equipo,",
    mobileTitle2: "en tu bolsillo.",
    mobileDesc: "Visualiza la agenda, ensaya con la secuencia virtual, y revisa cada detalle desde cualquier dispositivo. La experiencia móvil definitiva para tu equipo completo.",
    feat1Title: "Reproductor Nativo",
    feat1Desc: "Reproduce multitracks y secuencias con control total desde una experiencia diseñada para músicos.",
    feat2Title: "Sala de Previsualización",
    feat2Desc: "Ensaya y revisa tus secuencias antes del show con una vista clara para preparar cada detalle.",
    feat3Title: "Central de Multitracks",
    feat3Desc: "Sube, organiza y accede a tus pistas, stems y recursos desde un solo lugar.",
    feat4Title: "Eventos y Shows",
    feat4Desc: "Organiza fechas, ensayos y presentaciones para que todo tu equipo esté alineado.",
    feat5Title: "Repertorios y Recursos",
    feat5Desc: "Centraliza canciones, charts, letras, links y materiales clave para cada presentación.",
    feat6Title: "Pads y Drum Machine",
    feat6Desc: "Suma Ambient Pads y una drum machine personalizable a tu interpretación en vivo, directo desde la app.",
    feat7Title: "Control Remoto",
    feat7Desc: "Play, pausa y stop de tu setlist desde el celular, en tiempo real, sin tocar la computadora del escenario.",
    whyTitle: "¿Por qué elegir",
    whyDesc: "A diferencia de otras soluciones que fragmentan tus recursos y cobran por cada función, nosotros lo unificamos todo en un solo ecosistema diseñado para tu organización completa.",
    tableFeat: "CARACTERÍSTICAS",
    tableOthers: "OTRAS APPS",
    f1: "Reproductor de Multitracks & DAW Nativo",
    f1O: "No disponible (App aparte)",
    f2: "Usuarios / Miembros",
    f2B: "Ilimitados (Elite)",
    f2O: "Limitado (Max 1000)",
    f3: "Almacenamiento para Stems/Pistas",
    f3B: "Hasta 50 GB",
    f3O: "Limitado (2GB - 11GB)",
    f4: "Eventos y Ensayos",
    f4B: "Ilimitados",
    f4O: "Limitado por plan",
    f5: "Charts en PDF y Letras",
    f6: "Costo para Equipos Grandes",
    pricingTitle: "Planes diseñados para cada etapa de tu equipo",
    pricingDesc: "Empieza gratis y escala cuando necesites más usuarios, más almacenamiento y herramientas avanzadas para preparar cada presentación.",
    monthly: "Mensual",
    annual: "Anual",
    save: "AHORRA 30%",
    freePlan: "Gratis",
    freeSub: "Ideal para equipos nuevos",
    f_band1: "1 organización",
    f_band3: "Hasta 3 organizaciones",
    f_band10: "Hasta 10 organizaciones",
    f_bandUl: "Organizaciones ilimitadas",
    f_user10: "Hasta 10 usuarios",
    f_stor300: "300 MB almacenamiento",
    f_cal: "Calendario de eventos",
    f_rep: "Repertorios básicos",
    f_lyrics: "Letras",
    f_yt: "Enlaces de YouTube",
    starterPlan: "Starter",
    starterSubMo: "Facturado mensualmente",
    starterSubYr: "Equivale a $6.2 / mes",
    f_user25: "Hasta 25 usuarios",
    f_stor10: "10 GB almacenamiento",
    f_pdf: "Charts en PDF",
    f_mgr: "Gestión de repertorios",
    f_res: "Recursos por canción",
    f_multi: "Multitracks",
    f_player: "Reproductor en la app",
    f_daw: "Bandly DAW",
    f_dawDesc: "El estudio de grabación integrado: sube, mezcla y reproduce tus multipistas en vivo, sin depender de otra app aparte.",
    proPlan: "Pro",
    proSubMo: "Facturado mensualmente",
    proSubYr: "Equivale a $13.2 / mes",
    f_user75: "Hasta 75 usuarios",
    f_stor45: "45 GB almacenamiento",
    f_allStarter: "Todo lo de Starter",
    f_preview: "Sala de previsualización",
    f_seqPlayer: "Player de secuencias",
    f_presenter: "Bandly Presenter (App de Proyección)",
    elitePlan: "Elite",
    eliteSubMo: "Facturado mensualmente",
    eliteSubYr: "Equivale a $27.4 / mes",
    f_userUl: "Usuarios ilimitados",
    f_stor100: "100 GB almacenamiento",
    f_allPro: "Todo lo de Pro",
    f_dmx: "Bandly Lights (Control DMX/Art-Net)",
    f_roles: "Roles y permisos",
    f_support: "Prioridad en soporte",
    f_early: "Acceso anticipado",
    ctaTitle: "¿Listo para llevar tu equipo a otro nivel?",
    ctaDesc: "Organiza mejor cada show, centraliza tus recursos y ensaya con más control desde una sola plataforma.",
    ctaBtn: "Comenzar gratis",
    footTerms: "Términos",
    footPriv: "Privacidad",
    footRefund: "Reembolsos",
    footContact: "Contacto",
    footOp: "Operado por Johan Sebastian Jimenez Calderon • Bogotá, Colombia",
    footRights: "© 2026 Bandly Live Engine. Todos los derechos reservados.",
    monthLabel: "/mes",
    yearLabel: "/año",
    chooseStarter: "Elegir Starter",
    choosePro: "Elegir Pro",
    chooseElite: "Elegir Elite"
  },
  en: {
    navFeatures: "Features",
    navPricing: "Pricing",
    navCommunity: "Community",
    navSupport: "Support",
    btnLogin: "Log In",
    btnSignup: "Try for Free",
    heroMain: "All your music.",
    heroSub: "Under control.",
    heroDesc: "The engine that syncs your music, your lyrics and your lights in real time — so on stage, everything moves as one.",
    heroTags: "Events • Setlists • Resources • Multitracks • Sequences",
    btnStart: "Start Now",
    btnViewPlans: "View Plans",
    availableOn: "Available on",
    webTitle: "Web Management & Rehearsal",
    webDesc: "Organize your events, plan setlists, and rehearse with your stems from any browser.",
    desktopTitle: "Native App (Windows / Mac)",
    desktopDesc: "The professional tool to play your live sequences with zero latency and maximum stability.",
    premiumMini: "NOTHING COMPARES",
    premiumMain1: "One marker moves your audio, your lyrics",
    premiumMain2: "and your lights,",
    premiumMain3: "at the exact same time.",
    premiumSupport1: "It's not just another feature. It's",
    premiumSupport2: "how every show moves:",
    premiumSupport3: "Bandly DAW's markers trigger the on-screen lyric change and the lighting scene at the exact same instant.",
    syncBadge1: "Bandly DAW",
    syncBadge1Desc: "Zero-latency multitracks",
    syncBadge2: "Lyrics",
    syncBadge2Desc: "Bandly Presenter on screen",
    syncBadge3: "Lights",
    syncBadge3Desc: "Bandly Lights (DMX/Art-Net)",
    proPlayerTitle1: "The Only Native Multitrack Player",
    proPlayerTitle2: "for Windows and Mac.",
    proPlayerDesc: "Unlike other web platforms, Bandly has its own installable audio engine. Manage all your simultaneous multitracks with zero latency. Designed specifically for musicians who need absolute reliability on stage.",
    proFeat1: "Arrange without re-exporting",
    proFeat1Desc: "Skip verse 2 or repeat the chorus in one click. The original audio is never cut — undo it just as easily.",
    proFeat2: "Real multichannel routing",
    proFeat2Desc: "Send every track to the physical output you want: click to 3, tracks to 1-2, pads to 5-6. Native ASIO.",
    proFeat3: "3-band EQ per track",
    proFeat3Desc: "EQ every channel inside the app, no separate console.",
    proFeat4: "Click on its own output",
    proFeat4Desc: "Plus a bar-counted pre-roll before you come in.",
    proFeat5: "Local sync",
    proFeat5Desc: "Download and play without relying on the internet.",
    proFeat6: "Hardware resilience",
    proFeat6Desc: "If the interface drops mid-show, it reconnects itself.",
    presenterMini: "LIVE PROJECTION",
    presenterTitle1: "Bandly Presenter,",
    presenterTitle2: "on-screen lyrics with no extra operator.",
    presenterDesc: "The desktop app for projecting lyrics and content during your events — automatically synced with what's happening in the DAW, with no one manually switching slides.",
    presenterFeat1: "Automatic sync",
    presenterFeat1Desc: "DAW section markers change the on-screen slide by themselves, in real time.",
    presenterFeat2: "Stage Display",
    presenterFeat2Desc: "A separate window for the platform team: current lyric, next line, and a clock — no need to look at the audience screen.",
    presenterFeat3: "Backgrounds and images per song",
    presenterFeat3Desc: "Every song with its own background, font, and style, ready ahead of the event.",
    mobileTitle1: "Your entire team,",
    mobileTitle2: "in your pocket.",
    mobileDesc: "View the schedule, rehearse with the virtual sequence, and review every detail from any device. The ultimate mobile experience for your whole team.",
    feat1Title: "Native Player",
    feat1Desc: "Play multitracks and sequences with full control from an experience designed for musicians.",
    feat2Title: "Preview Room",
    feat2Desc: "Rehearse and review your sequences before the show with a clear view to prepare every detail.",
    feat3Title: "Multitrack Hub",
    feat3Desc: "Upload, organize, and access your tracks, stems, and resources from one place.",
    feat4Title: "Events and Shows",
    feat4Desc: "Organize dates, rehearsals, and presentations so your entire team is aligned.",
    feat5Title: "Setlists and Resources",
    feat5Desc: "Centralize songs, charts, lyrics, links, and key materials for every presentation.",
    feat6Title: "Pads & Drum Machine",
    feat6Desc: "Add Ambient Pads and a customizable drum machine to your live performance, right from the app.",
    feat7Title: "Remote Control",
    feat7Desc: "Play, pause and stop your setlist from your phone, in real time, without touching the stage computer.",
    whyTitle: "Why choose",
    whyDesc: "Unlike other solutions that fragment your resources and charge per feature, we unify everything into a single ecosystem designed for your whole organization.",
    tableFeat: "FEATURES",
    tableOthers: "OTHER APPS",
    f1: "Multitrack Player & Native DAW",
    f1O: "Not available (Separate app)",
    f2: "Users / Members",
    f2B: "Unlimited (Elite)",
    f2O: "Limited (Max 1000)",
    f3: "Storage for Stems/Tracks",
    f3B: "Up to 50 GB",
    f3O: "Limited (2GB - 11GB)",
    f4: "Events and Rehearsals",
    f4B: "Unlimited",
    f4O: "Limited by plan",
    f5: "PDF Charts and Lyrics",
    f6: "Cost for Large Teams",
    pricingTitle: "Plans designed for every stage of your team",
    pricingDesc: "Start for free and scale when you need more users, more storage, and advanced tools to prepare every presentation.",
    monthly: "Monthly",
    annual: "Annual",
    save: "SAVE 30%",
    freePlan: "Free",
    freeSub: "Ideal for new bands",
    f_band1: "1 organization",
    f_band3: "Up to 3 organizations",
    f_band10: "Up to 10 organizations",
    f_bandUl: "Unlimited organizations",
    f_user10: "Up to 10 users",
    f_stor300: "300 MB storage",
    f_cal: "Event calendar",
    f_rep: "Basic setlists",
    f_lyrics: "Lyrics",
    f_yt: "YouTube Links",
    starterPlan: "Starter",
    starterSubMo: "Billed monthly",
    starterSubYr: "Equals $6.2 / month",
    f_user25: "Up to 25 users",
    f_stor10: "10 GB storage",
    f_pdf: "PDF Charts",
    f_mgr: "Setlist management",
    f_res: "Resources per song",
    f_multi: "Multitracks",
    f_player: "In-app player",
    f_daw: "Bandly DAW",
    f_dawDesc: "The built-in recording studio: upload, mix and play your live multitracks — no separate app needed.",
    proPlan: "Pro",
    proSubMo: "Billed monthly",
    proSubYr: "Equals $13.2 / month",
    f_user75: "Up to 75 users",
    f_stor45: "45 GB storage",
    f_allStarter: "Everything in Starter",
    f_preview: "Preview room",
    f_seqPlayer: "Sequence player",
    f_presenter: "Bandly Presenter (Desktop App)",
    elitePlan: "Elite",
    eliteSubMo: "Billed monthly",
    eliteSubYr: "Equals $27.4 / month",
    f_userUl: "Unlimited users",
    f_stor100: "100 GB storage",
    f_allPro: "Everything in Pro",
    f_dmx: "Bandly Lights (DMX/Art-Net Control)",
    f_roles: "Roles and permissions",
    f_support: "Priority support",
    f_early: "Early access",
    ctaTitle: "Ready to take your band to another level?",
    ctaDesc: "Organize every show better, centralize your resources, and rehearse with more control from a single platform.",
    ctaBtn: "Start for free",
    footTerms: "Terms",
    footPriv: "Privacy",
    footRefund: "Refunds",
    footContact: "Contact",
    footOp: "Operated by Johan Sebastian Jimenez Calderon • Bogotá, Colombia",
    footRights: "© 2026 Bandly Live Engine. All rights reserved.",
    monthLabel: "/mo",
    yearLabel: "/yr",
    chooseStarter: "Choose Starter",
    choosePro: "Choose Pro",
    chooseElite: "Choose Elite"
  }
};
