export const landingDict = {
  es: {
    navFeatures: "Funciones",
    navPricing: "Planes",
    navCommunity: "Comunidad",
    navSupport: "Soporte",
    btnLogin: "Iniciar Sesión",
    btnSignup: "Probar Gratis",
    heroMain: "Toda tu música.",
    heroSub: "Bajo control.",
    heroDesc: "Organiza tu banda y toda tu organización — producción, logística, sonido y bienvenida — desde una sola plataforma.",
    heroTags: "Eventos • Repertorios • Recursos • Multitracks • Secuencias",
    btnStart: "Empezar Ahora",
    btnViewPlans: "Ver planes",
    availableOn: "Disponible en",
    webTitle: "Gestión & Ensayo Web",
    webDesc: "Organiza tus eventos, planea repertorios y ensaya con tus stems desde cualquier navegador.",
    desktopTitle: "App Nativa (Windows / Mac)",
    desktopDesc: "La herramienta profesional para reproducir tus secuencias en vivo con latencia cero y máxima estabilidad.",
    premiumMini: "NO ES SOLO PARA LA BANDA",
    premiumMain1: "Organiza tu banda, tu equipo de producción",
    premiumMain2: "y toda tu organización desde",
    premiumMain3: "una sola plataforma.",
    premiumSupport1: "Pensado para equipos de producción de eventos que quieren trabajar con",
    premiumSupport2: "más orden, menos caos",
    premiumSupport3: "y una experiencia más completa.",
    proPlayerTitle1: "El Único Reproductor de Multitracks Nativo",
    proPlayerTitle2: "para Windows y Mac.",
    proPlayerDesc: "A diferencia de otras plataformas web, Bandly cuenta con su propio motor de audio instalable. Gestiona todos tus multitracks simultáneos con latencia cero. Diseñado específicamente para músicos que necesitan fiabilidad absoluta en el escenario.",
    proFeat1: "Audio Multicanal",
    proFeat1Desc: "Control independiente de volumen y ruteo por track.",
    proFeat2: "Sincronización Local",
    proFeat2Desc: "Descarga y reproduce sin depender del internet.",
    proFeat3: "Resiliencia de Hardware",
    proFeat3Desc: "Recuperación instantánea ante desconexiones.",
    presenterMini: "PROYECCIÓN EN VIVO",
    presenterTitle1: "Bandly Presenter,",
    presenterTitle2: "letras en pantalla sin operador extra.",
    presenterDesc: "La app de escritorio para proyectar letras y contenido durante tus eventos — sincronizada automáticamente con lo que pasa en el DAW, sin que nadie tenga que estar cambiando diapositivas a mano.",
    presenterFeat1: "Sincronización automática",
    presenterFeat1Desc: "Los marcadores de sección del DAW cambian la diapositiva en pantalla solos, en tiempo real.",
    presenterFeat2: "Stage Display",
    presenterFeat2Desc: "Ventana aparte para el escenario: letra actual, siguiente línea y reloj — sin mirar la pantalla de la audiencia.",
    presenterFeat3: "Fondos e imágenes por canción",
    presenterFeat3Desc: "Cada canción con su propio fondo, tipografía y estilo, listos desde antes del evento.",
    mobileTitle1: "Todo tu equipo,",
    mobileTitle2: "en tu bolsillo.",
    mobileDesc: "Visualiza la agenda, ensaya con la secuencia virtual, y revisa cada detalle desde cualquier dispositivo. La experiencia móvil definitiva para tu equipo completo.",
    feat1Title: "Reproductor Nativo",
    feat1Desc: "Reproduce multitracks y secuencias con control total desde una experiencia diseñada para músicos.",
    feat2Title: "Sala de Previsualización",
    feat2Desc: "Ensaya y revisa tus secuencias antes del show con una vista clara para preparar cada detalle.",
    feat3Title: "Central de Multitracks",
    feat3Desc: "Sube, organiza y accede a tus pistas, stems y recursos desde un solo lugar.",
    feat4Title: "Eventos y Shows",
    feat4Desc: "Organiza fechas, ensayos y presentaciones para que todo tu equipo esté alineado.",
    feat5Title: "Repertorios y Recursos",
    feat5Desc: "Centraliza canciones, charts, letras, links y materiales clave para cada presentación.",
    whyTitle: "¿Por qué elegir",
    whyDesc: "A diferencia de otras soluciones que fragmentan tus recursos y cobran por cada función, nosotros lo unificamos todo en un solo ecosistema diseñado para tu organización completa.",
    tableFeat: "CARACTERÍSTICAS",
    tableOthers: "OTRAS APPS",
    f1: "Reproductor de Multitracks & DAW Nativo",
    f1O: "No disponible (App aparte)",
    f2: "Usuarios / Miembros",
    f2B: "Ilimitados (Elite)",
    f2O: "Limitado (Max 1000)",
    f3: "Almacenamiento para Stems/Pistas",
    f3B: "Hasta 50 GB",
    f3O: "Limitado (2GB - 11GB)",
    f4: "Eventos y Ensayos",
    f4B: "Ilimitados",
    f4O: "Limitado por plan",
    f5: "Charts en PDF y Letras",
    f6: "Costo para Equipos Grandes",
    pricingTitle: "Planes diseñados para cada etapa de tu equipo",
    pricingDesc: "Empieza gratis y escala cuando necesites más usuarios, más almacenamiento y herramientas avanzadas para preparar cada presentación.",
    monthly: "Mensual",
    annual: "Anual",
    save: "AHORRA 30%",
    freePlan: "Gratis",
    freeSub: "Ideal para equipos nuevos",
    f_band1: "1 equipo u organización",
    f_user10: "Hasta 10 usuarios",
    f_stor300: "300 MB almacenamiento",
    f_cal: "Calendario de eventos",
    f_rep: "Repertorios básicos",
    f_lyrics: "Letras",
    f_yt: "Enlaces de YouTube",
    starterPlan: "Starter",
    starterSubMo: "Facturado mensualmente",
    starterSubYr: "Equivale a $6.2 / mes",
    f_band3: "Hasta 3 equipos",
    f_user25: "Hasta 25 usuarios",
    f_stor10: "10 GB almacenamiento",
    f_pdf: "Charts en PDF",
    f_mgr: "Gestión de repertorios",
    f_res: "Recursos por canción",
    f_multi: "Multitracks",
    f_player: "Reproductor en la app",
    proPlan: "Pro",
    proSubMo: "Facturado mensualmente",
    proSubYr: "Equivale a $13.2 / mes",
    f_band10: "Hasta 10 equipos",
    f_user75: "Hasta 75 usuarios",
    f_stor45: "45 GB almacenamiento",
    f_allStarter: "Todo lo de Starter",
    f_preview: "Sala de previsualización",
    f_seqPlayer: "Player de secuencias",
    f_presenter: "Bandly Presenter (App de Proyección)",
    elitePlan: "Elite",
    eliteSubMo: "Facturado mensualmente",
    eliteSubYr: "Equivale a $27.4 / mes",
    f_bandUl: "Equipos ilimitados",
    f_userUl: "Usuarios ilimitados",
    f_stor100: "100 GB almacenamiento",
    f_allPro: "Todo lo de Pro",
    f_roles: "Roles y permisos",
    f_support: "Prioridad en soporte",
    f_early: "Acceso anticipado",
    ctaTitle: "¿Listo para llevar tu equipo a otro nivel?",
    ctaDesc: "Organiza mejor cada show, centraliza tus recursos y ensaya con más control desde una sola plataforma.",
    ctaBtn: "Comenzar gratis",
    footTerms: "Términos",
    footPriv: "Privacidad",
    footRefund: "Reembolsos",
    footContact: "Contacto",
    footOp: "Operado por Johan Sebastian Jimenez Calderon • Bogotá, Colombia",
    footRights: "© 2026 Bandly Live Engine. Todos los derechos reservados.",
    monthLabel: "/mes",
    yearLabel: "/año",
    chooseStarter: "Elegir Starter",
    choosePro: "Elegir Pro",
    chooseElite: "Elegir Elite"
  },
  en: {
    navFeatures: "Features",
    navPricing: "Pricing",
    navCommunity: "Community",
    navSupport: "Support",
    btnLogin: "Log In",
    btnSignup: "Try for Free",
    heroMain: "All your music.",
    heroSub: "Under control.",
    heroDesc: "Organize your band and your whole organization — production, logistics, sound, and welcome team — from a single platform.",
    heroTags: "Events • Setlists • Resources • Multitracks • Sequences",
    btnStart: "Start Now",
    btnViewPlans: "View Plans",
    availableOn: "Available on",
    webTitle: "Web Management & Rehearsal",
    webDesc: "Organize your events, plan setlists, and rehearse with your stems from any browser.",
    desktopTitle: "Native App (Windows / Mac)",
    desktopDesc: "The professional tool to play your live sequences with zero latency and maximum stability.",
    premiumMini: "NOT JUST FOR THE BAND",
    premiumMain1: "Organize your band, your production team",
    premiumMain2: "and your whole organization from",
    premiumMain3: "a single platform.",
    premiumSupport1: "Designed for event production teams who want to work with",
    premiumSupport2: "more order, less chaos",
    premiumSupport3: "and a more complete experience.",
    proPlayerTitle1: "The Only Native Multitrack Player",
    proPlayerTitle2: "for Windows and Mac.",
    proPlayerDesc: "Unlike other web platforms, Bandly has its own installable audio engine. Manage all your simultaneous multitracks with zero latency. Designed specifically for musicians who need absolute reliability on stage.",
    proFeat1: "Multichannel Audio",
    proFeat1Desc: "Independent volume and routing control per track.",
    proFeat2: "Local Synchronization",
    proFeat2Desc: "Download and play without relying on the internet.",
    proFeat3: "Hardware Resilience",
    proFeat3Desc: "Instant recovery from disconnections.",
    presenterMini: "LIVE PROJECTION",
    presenterTitle1: "Bandly Presenter,",
    presenterTitle2: "on-screen lyrics with no extra operator.",
    presenterDesc: "The desktop app for projecting lyrics and content during your events — automatically synced with what's happening in the DAW, with no one manually switching slides.",
    presenterFeat1: "Automatic sync",
    presenterFeat1Desc: "DAW section markers change the on-screen slide by themselves, in real time.",
    presenterFeat2: "Stage Display",
    presenterFeat2Desc: "A separate window for the platform team: current lyric, next line, and a clock — no need to look at the audience screen.",
    presenterFeat3: "Backgrounds and images per song",
    presenterFeat3Desc: "Every song with its own background, font, and style, ready ahead of the event.",
    mobileTitle1: "Your entire team,",
    mobileTitle2: "in your pocket.",
    mobileDesc: "View the schedule, rehearse with the virtual sequence, and review every detail from any device. The ultimate mobile experience for your whole team.",
    feat1Title: "Native Player",
    feat1Desc: "Play multitracks and sequences with full control from an experience designed for musicians.",
    feat2Title: "Preview Room",
    feat2Desc: "Rehearse and review your sequences before the show with a clear view to prepare every detail.",
    feat3Title: "Multitrack Hub",
    feat3Desc: "Upload, organize, and access your tracks, stems, and resources from one place.",
    feat4Title: "Events and Shows",
    feat4Desc: "Organize dates, rehearsals, and presentations so your entire team is aligned.",
    feat5Title: "Setlists and Resources",
    feat5Desc: "Centralize songs, charts, lyrics, links, and key materials for every presentation.",
    whyTitle: "Why choose",
    whyDesc: "Unlike other solutions that fragment your resources and charge per feature, we unify everything into a single ecosystem designed for your whole organization.",
    tableFeat: "FEATURES",
    tableOthers: "OTHER APPS",
    f1: "Multitrack Player & Native DAW",
    f1O: "Not available (Separate app)",
    f2: "Users / Members",
    f2B: "Unlimited (Elite)",
    f2O: "Limited (Max 1000)",
    f3: "Storage for Stems/Tracks",
    f3B: "Up to 50 GB",
    f3O: "Limited (2GB - 11GB)",
    f4: "Events and Rehearsals",
    f4B: "Unlimited",
    f4O: "Limited by plan",
    f5: "PDF Charts and Lyrics",
    f6: "Cost for Large Teams",
    pricingTitle: "Plans designed for every stage of your team",
    pricingDesc: "Start for free and scale when you need more users, more storage, and advanced tools to prepare every presentation.",
    monthly: "Monthly",
    annual: "Annual",
    save: "SAVE 30%",
    freePlan: "Free",
    freeSub: "Ideal for new bands",
    f_band1: "1 band or organization",
    f_user10: "Up to 10 users",
    f_stor300: "300 MB storage",
    f_cal: "Event calendar",
    f_rep: "Basic setlists",
    f_lyrics: "Lyrics",
    f_yt: "YouTube Links",
    starterPlan: "Starter",
    starterSubMo: "Billed monthly",
    starterSubYr: "Equals $6.2 / month",
    f_band3: "Up to 3 bands",
    f_user25: "Up to 25 users",
    f_stor10: "10 GB storage",
    f_pdf: "PDF Charts",
    f_mgr: "Setlist management",
    f_res: "Resources per song",
    f_multi: "Multitracks",
    f_player: "In-app player",
    proPlan: "Pro",
    proSubMo: "Billed monthly",
    proSubYr: "Equals $13.2 / month",
    f_band10: "Up to 10 bands",
    f_user75: "Up to 75 users",
    f_stor45: "45 GB storage",
    f_allStarter: "Everything in Starter",
    f_preview: "Preview room",
    f_seqPlayer: "Sequence player",
    f_presenter: "Bandly Presenter (Desktop App)",
    elitePlan: "Elite",
    eliteSubMo: "Billed monthly",
    eliteSubYr: "Equals $27.4 / month",
    f_bandUl: "Unlimited bands",
    f_userUl: "Unlimited users",
    f_stor100: "100 GB storage",
    f_allPro: "Everything in Pro",
    f_roles: "Roles and permissions",
    f_support: "Priority support",
    f_early: "Early access",
    ctaTitle: "Ready to take your band to another level?",
    ctaDesc: "Organize every show better, centralize your resources, and rehearse with more control from a single platform.",
    ctaBtn: "Start for free",
    footTerms: "Terms",
    footPriv: "Privacy",
    footRefund: "Refunds",
    footContact: "Contact",
    footOp: "Operated by Johan Sebastian Jimenez Calderon • Bogotá, Colombia",
    footRights: "© 2026 Bandly Live Engine. All rights reserved.",
    monthLabel: "/mo",
    yearLabel: "/yr",
    chooseStarter: "Choose Starter",
    choosePro: "Choose Pro",
    chooseElite: "Choose Elite"
  }
};
